server:
  port: 8082
spring:
  mail:
    host: smtp.126.com
    protocol: smtp
    default-encoding: UTF-8
    password: VMZKZETRYNQZDVEA
    username: wchao190@126.com
    port: 25
  rabbitmq:
    username: admin
    password: 123456
    host: 101.132.137.4
    port: 5672